# Generated by Django 5.1.1 on 2025-01-24 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalGameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_type", models.CharField(default="Local", max_length=15)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "opponent_username",
                    models.CharField(default="Player2", max_length=100),
                ),
                (
                    "tournamentID",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("my_score", models.PositiveIntegerField(default=0)),
                ("opponent_score", models.PositiveIntegerField(default=0)),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteGameLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("game_type", models.CharField(default="Remote", max_length=15)),
                ("winner_score", models.PositiveIntegerField(default=0)),
                ("loser_score", models.PositiveIntegerField(default=0)),
                (
                    "loserID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_lost",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="remote_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "winnerID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicTacToeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_type", models.CharField(default="TicTacToe", max_length=15)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "opponent_username",
                    models.CharField(default="Player2", max_length=100),
                ),
                ("my_score", models.PositiveIntegerField(default=0)),
                ("opponent_score", models.PositiveIntegerField(default=0)),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ttt_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
