# Generated by Django 5.1.1 on 2025-01-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamelog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localgamelog",
            name="game_type",
        ),
        migrations.RemoveField(
            model_name="remotegamelog",
            name="game_type",
        ),
        migrations.RemoveField(
            model_name="tictactoelog",
            name="game_type",
        ),
    ]
