# Generated by Django 5.1.1 on 2025-03-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamelog", "0005_alter_localgamelog_tournament_round"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tictactoelog",
            old_name="loserID",
            new_name="player1",
        ),
        migrations.RenameField(
            model_name="tictactoelog",
            old_name="loser_score",
            new_name="player1_score",
        ),
        migrations.RenameField(
            model_name="tictactoelog",
            old_name="winnerID",
            new_name="player2",
        ),
        migrations.RenameField(
            model_name="tictactoelog",
            old_name="winner_score",
            new_name="player2_score",
        ),
    ]
