# Generated by Django 5.1.1 on 2025-03-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamelog", "0008_remove_tictactoelog_player1_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="remotegamelog",
            old_name="loserID",
            new_name="loser",
        ),
        migrations.RenameField(
            model_name="remotegamelog",
            old_name="winnerID",
            new_name="winner",
        ),
    ]
