services:
    backend:
        build: backend/.
        environment:
            - HOST_IP=${HOST_IP}
        ports:
            - 8000:8000
        env_file:
            .env
        networks:
            - backend-db
            - frontend-backend
        depends_on:
            db:
              condition: service_healthy
        command: >
            sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: mypassword
        expose:
            - 5432
        ports:
            - 8001:5432
        restart: always
        networks:
            - backend-db
        volumes:
            - ./data/db:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "postgres"]
          interval: 5s
          retries: 5
          timeout: 3s

    frontend:
        build: frontend/.
        ports:
            - 80:80
            - 443:443
        networks:
            - frontend-backend
        volumes:
            - ./frontend/:/usr/share/nginx/html
        restart: always
        depends_on:
            - backend

networks:
    backend-db:
        name: backend-db
        driver: bridge
    frontend-backend:
        name: frontend-backend
        driver: bridge
