# Generated by Django 5.1.1 on 2024-11-20 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(default="MATCHMAKING", max_length=10)),
                ("map_round_1", models.CharField(default="---------", max_length=9)),
                ("map_round_2", models.CharField(default="---------", max_length=9)),
                ("map_round_3", models.CharField(default="---------", max_length=9)),
                ("current_round", models.IntegerField(default=1)),
                ("last_play_time", models.DateTimeField(auto_now=True)),
                (
                    "game_winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_winner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "next_to_play",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_to_play",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner_round_1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winner_round_1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner_round_2",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winner_round_2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner_round_3",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winner_round_3",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
