# Generated by Django 5.1.1 on 2024-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0002_alter_game_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(default="MATCHMAKING", max_length=11),
        ),
    ]
