import {
    ActivateAccount,
    ActivateAccountContent,
    SignIn,
    SignInContent,
    SignUp,
    SignUpContent,
    TwoFactorAuth,
  } from './authentication';
  
  import {
    Home,
    HomeContent,
  } from './home';
  import {
    ResetPassword,
    ResetPasswordCode,
    ResetPasswordEmail,
    ResetPasswordNew,
  } from './reset_password';
  export {
    ActivateAccount,
    ActivateAccountContent,
    SignIn,
    SignInContent,
    SignUp,
    SignUpContent,
    TwoFactorAuth,
    Home,
    HomeContent,
    Local,
    PrivacyPolicy,
    PrivacyPolicyContent,
    Ranking,
    RankingContent,
    ResetPassword,
    ResetPasswordCode,
    ResetPasswordEmail,
    ResetPasswordNew,
    Settings,
    Settings2FA,
    SettingsContent,
    TournamentBracket,
    TournamentCreate,
    TournamentCreateContent,
    TournamentDetails,
    Tournaments,
    TournamentsContent,
    TournamentsList,
    UserProfile,
    UserProfileChart,
    UserProfileChartsCards,
    UserProfileContent,
    UserProfileHeader,
    UserProfileMatchList,
    UserProfileStatsCard,
    UserProfileStatsCards,
    NotFound,
  };