# Generated by Django 5.1.1 on 2025-02-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_pong", "0002_matchmakingqueue"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchmakingqueue",
            name="systemID",
            field=models.TextField(blank=True, null=True),
        ),
    ]
