# Generated by Django 5.1.1 on 2024-11-21 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamemodel",
            name="user",
        ),
        migrations.AddField(
            model_name="gamemodel",
            name="users",
            field=models.ManyToManyField(
                related_name="games", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
