# Generated by Django 5.1.1 on 2024-12-18 06:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_gamemodel_user_gamemodel_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalGameLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_type", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "localOpponent",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tournamentID",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("my_score", models.PositiveIntegerField()),
                ("opponent_score", models.PositiveIntegerField()),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="local_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemoteGameLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "game_type",
                    models.CharField(
                        choices=[("PONG", "Pong"), ("TIC-TAC-TOE", "Tic-Tac-Toe")],
                        max_length=15,
                    ),
                ),
                ("my_score", models.PositiveIntegerField()),
                ("opponent_score", models.PositiveIntegerField()),
                ("is_win", models.BooleanField(default=False)),
                (
                    "loserID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_lost",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="remote_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "winnerID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GameModel",
        ),
    ]
