# Generated by Django 5.1.1 on 2024-12-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_localgamelog_remotegamelog_delete_gamemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="remotegamelog",
            name="is_win",
        ),
        migrations.RemoveField(
            model_name="remotegamelog",
            name="my_score",
        ),
        migrations.RemoveField(
            model_name="remotegamelog",
            name="opponent_score",
        ),
    ]
