# Generated by Django 5.1.1 on 2024-12-20 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_remotegamelog_loser_score_remotegamelog_winner_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="localgamelog",
            name="game_type",
            field=models.CharField(default="Local", max_length=100),
        ),
        migrations.AlterField(
            model_name="localgamelog",
            name="my_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="localgamelog",
            name="opponent_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="localgamelog",
            name="users",
        ),
        migrations.AlterField(
            model_name="remotegamelog",
            name="game_type",
            field=models.CharField(default="Remote", max_length=15),
        ),
        migrations.AlterField(
            model_name="remotegamelog",
            name="loser_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="remotegamelog",
            name="winner_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="localgamelog",
            name="users",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_games",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
