# Generated by Django 5.1.1 on 2024-12-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_localgamelog_game_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="localgamelog",
            old_name="localOpponent",
            new_name="opponent_username",
        ),
    ]
