# Generated by Django 5.1.1 on 2024-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_email_otp_customuser_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
