# Generated by Django 5.1.1 on 2024-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_otp_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enable_otp",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
