# Generated by Django 5.1.1 on 2024-11-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="image",
            new_name="avatar",
        ),
    ]
