# Generated by Django 5.1.1 on 2024-11-12 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_image_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
