# Generated by Django 5.1.1 on 2024-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="enable_otp",
            field=models.BooleanField(default=False),
        ),
    ]
