# Generated by Django 5.1.1 on 2024-11-12 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_is_online_customuser_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
