# Generated by Django 5.1.1 on 2024-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_customuser_enable_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
