# Generated by Django 5.1.1 on 2024-12-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_customuser_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                default="default_avatar/default_avatar.jpg",
                null=True,
                upload_to="images/",
            ),
        ),
    ]
