# Generated by Django 5.1.1 on 2024-11-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_game_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="game_id",
        ),
    ]
