# Generated by Django 5.1.1 on 2024-12-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
