# Generated by Django 5.1.1 on 2024-12-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_customuser_avatar"),
        ("users", "0011_remove_customuser_game_id"),
    ]

    operations = []
