# Generated by Django 5.1.1 on 2025-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_merge_20241222_0621"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_web_connected",
            field=models.BooleanField(default=False),
        ),
    ]
