# Generated by Django 5.1.1 on 2025-01-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_customuser_is_web_connected"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_web_connected",
        ),
    ]
